# Define stages wich are to be executed
stages:
  - build

# Linux build
build_linux:
  stage: build
  image: debian:stable
  script:
    - echo "try to build something on linux"
    - echo "success"
