# Define stages wich are to be executed
stages:
  - build

# Linux build
build_linux:
  stage: build
  image: debian:stable
  script:
    - apt update
    - apt install -y gcc g++ clang-format
    - clang-format --version
    - gcc --version
    - g++ --version
