# Define stages wich are to be executed
stages:


# Use the official gcc image, based on debian (see https://hub.docker.com/_/gcc/)
image: gcc

# Build
build:
  stage: build
  before_script:
    - apt update
    - apt install -y make
  script:
    - make BIN=bin
  artifacts:
    paths:
    - bin

# Test
test:
  stage: test
  script:
    - ./run.sh

# Code quality
code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]
