# Define stages wich are to be executed
stages:

# Use the official gcc image, based on debian (see https://hub.docker.com/_/gcc/)
image: gcc

# Build
build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y make
  script:
    - make BIN=bin
  artifacts:
    paths:
    - bin

# Test
run:
  stage: test
  script:
    - ./run.sh

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]
