# Define stages wich are to be executed
stages:

# Linux build
build_linux:
  image: ubuntu:18.04
  script:
    - apt update
    - apt install -y make
    - make --version
    - apt install -y gcc g++
    - gcc --version
    - g++ --version
    - apt install -y clang clang-format
    - clang --version
    - clang++ --version
    - clang-format --version

# Code quality
codequality:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > codeclimate.json
  artifacts:
    paths: [codeclimate.json]
