# Define stages wich are to be executed
stages:
  - build

# Linux build
build_linux:
  stage: build
  image: ubuntu:18.04
  script:
    - apt update
    - apt install -y make
    - make --version
    - apt install -y gcc g++
    - gcc --version
    - g++ --version
    - apt install -y clang clang++ clang-format
    - clang --version
    - clang++ --version
    - clang-format --version
