this.fuzzer:=$(call get-my-dir)

PEANUTS_FUZZER_NAME:=fuzzer.exe

PEANUTS_FUZZER_TARGET:=$(PEANUTS_FUZZER_NAME:%.exe=%)

PEANUTS_FUZZER_SRCS:=\
	$(this.fuzzer)/srcs/fuzzer.cpp\
	$(this.fuzzer)/srcs/example.cpp\

PEANUTS_FUZZER_OBJS:=\
	$(PEANUTS_FUZZER_SRCS:%=$(BIN)/%.o)

INCLUDES+=-I$(INCLUDE)

$(BIN)/$(PEANUTS_FUZZER_NAME):\
	$(PEANUTS_FUZZER_OBJS)\

$(PEANUTS_FUZZER_TARGET): $(BIN)/$(PEANUTS_FUZZER_NAME)

.PHONY: $(PEANUTS_FUZZER_TARGET)
TARGETS+=$(PEANUTS_FUZZER_TARGET)


