include utils.mk

this:=$(call get-my-dir)

all: true_all

BIN?=bin

include $(this)/build.mk

CFLAGS+=-Wall
CFLAGS+=-Wextra
CFLAGS+=-Werror
CFLAGS+=-pedantic-errors

include $(this)/peanuts-tester-requirements.mk

PEANUTS_TESTER_APP_NAME:=tester.exe
PEANUTS_TESTER_APP_TARGET:=$(PEANUTS_TESTER_APP_NAME:%.exe=%)

PEANUTS_TESTER_APP_SRCS:=\
	$(PEANUTS_TESTER_SRCS)\
	$(this)/srcs/example.cpp\

PEANUTS_TESTER_APP_OBJS:=\
	$(PEANUTS_TESTER_APP_SRCS:%=$(BIN)/%.o)

$(BIN)/$(PEANUTS_TESTER_APP_NAME):\
	$(PEANUTS_TESTER_APP_OBJS)\

$(PEANUTS_TESTER_APP_TARGET): INCLUDES+=$(PEANUTS_TESTER_INCLUDES)
$(PEANUTS_TESTER_APP_TARGET): $(BIN)/$(PEANUTS_TESTER_APP_NAME)

.PHONY: $(PEANUTS_TESTER_APP_TARGET)
TARGETS+=$(PEANUTS_TESTER_APP_TARGET)

include $(this)/peanuts-fuzzer-requirements.mk

PEANUTS_FUZZER_APP_NAME:=fuzzer.exe
PEANUTS_FUZZER_APP_TARGET:=$(PEANUTS_FUZZER_APP_NAME:%.exe=%)

PEANUTS_FUZZER_APP_SRCS:=\
	$(PEANUTS_FUZZER_SRCS)\
	$(this)/srcs/example.cpp\

PEANUTS_FUZZER_APP_OBJS:=\
	$(PEANUTS_FUZZER_APP_SRCS:%=$(BIN)/%.o)

$(BIN)/$(PEANUTS_FUZZER_APP_NAME):\
	$(PEANUTS_FUZZER_APP_OBJS)\

$(PEANUTS_FUZZER_APP_TARGET): INCLUDES+=$(PEANUTS_TESTER_INCLUDES)
$(PEANUTS_FUZZER_APP_TARGET): $(BIN)/$(PEANUTS_FUZZER_APP_NAME)

.PHONY: $(PEANUTS_FUZZER_APP_TARGET)
TARGETS+=$(PEANUTS_FUZZER_APP_TARGET)


true_all: $(TARGETS)
