this.tester:=$(call get-my-dir)

PEANUTS_TESTER_NAME:=tester.exe

PEANUTS_TESTER_TARGET:=$(PEANUTS_TESTER_NAME:%.exe=%)

PEANUTS_TESTER_SRCS:=\
	$(this.tester)/srcs/tester.cpp\
	$(this.tester)/srcs/example.cpp\

PEANUTS_TESTER_OBJS:=\
	$(PEANUTS_TESTER_SRCS:%=$(BIN)/%.o)

INCLUDES+=-I$(INCLUDE)

$(BIN)/$(PEANUTS_TESTER_NAME):\
	$(PEANUTS_TESTER_OBJS)\

$(PEANUTS_TESTER_TARGET): $(BIN)/$(PEANUTS_TESTER_NAME)

.PHONY: $(PEANUTS_TESTER_TARGET)
TARGETS+=$(PEANUTS_TESTER_TARGET)


